data<- read.csv("household.txt",header = T,sep = ";",dec = ".")
library(dplyr)
filtdata<-filter(data,Date=="1/2/2007"|Date=="2/2/2007")
filtdata$datetime<-as.POSIXct(paste(filtdata$Date,filtdata$Time),format="%d/%m/%Y %H:%M:%S")
png(filename = "plot3.png",width = 480,height = 480,units = "px")
plot(filtdata$datetime,filtdata$Sub_metering_1,type="n",xlab = "",ylab = "Energy sub metering",axis=FALSE)
axis(side=2, at=seq(0, 30, by=10))
legend ("topright",lty=c(1,1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
lines(filtdata$datetime,filtdata$Sub_metering_1,col="black")
lines(filtdata$datetime,filtdata$Sub_metering_2,col="red")
lines(filtdata$datetime,filtdata$Sub_metering_3,col="blue")
dev.off()